# Generated by Django 4.1.13 on 2024-05-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_id', models.CharField(max_length=20, unique=True)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prod_mfd', models.DateField()),
                ('prod_quan', models.IntegerField()),
                ('prod_supplier', models.CharField(max_length=50)),
            ],
        ),
    ]
