# Generated by Django 4.1.13 on 2024-05-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.IntegerField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_supplier',
            field=models.CharField(max_length=100),
        ),
    ]
