# Generated by Django 4.1.13 on 2024-05-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_product_prod_id_alter_product_prod_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.IntegerField(unique=True),
        ),
    ]
